---
title: "Responsi Praktikum Analisis Regresi Terapan"
author: "Cheisa Billy Putra Antoni"
date: "2026-05-25"
output: html_document
---

# NOMOR 2
```{r}
# Membuat data sintetis
x <- c(1:11, 16:21, 24:31)
y <- numeric(length(x))

# Segmen pertama
set.seed(456)
y[1:11] <- seq(10, 60, len = 11) + rnorm(11, 0, 3)

# Segmen kedua
set.seed(456)
y[12:17] <- seq(45, 15, len = 6) + rnorm(6, 0, 3)

# Segmen ketiga
set.seed(456)
y[18:25] <- seq(25, 70, len = 8) + rnorm(8, 0, 3)

x
y
```

```{r}
# ITERATIVE SEARCHING b1
breaks1 <- x[which(x >= 1 & x <= 21)]
mse1 <- numeric(length(breaks1))
for(i in 1:length(breaks1)){
  piecewise1 <- lm(y ~ x*(x < breaks1[i]) + x*(x >= breaks1[i]))
  mse1[i] <- summary(piecewise1)[6]
}
mse1 <- as.numeric(mse1)
b1 <- breaks1[which(mse1 == min(mse1))]
b1

# ITERATIVE SEARCHING b2
breaks2 <- x[which(x > b1)]
mse2 <- numeric(length(breaks2))
for(j in 1:length(breaks2)){
  piecewise2 <- lm(y ~ x*(x < b1) + x*(x >= b1 & x < breaks2[j]) + x*(x >= breaks2[j]))
  mse2[j] <- summary(piecewise2)[6]
}
mse2 <- as.numeric(mse2)
b2 <- breaks2[which(mse2 == min(mse2))]
b2
```

```{r}
# Model Regresi
piecewise_final <- lm(y ~ x*(x < b1) + x*(x >= b1 & x < b2) + x*(x >= b2))
summary(piecewise_final)
```

```{r}
## Plot it
plot(x,y, ylim=c(0, 80), pch=16)
curve((-138.4587 + 142.0703) + (6.7429 - 1.5453)*x, add=T, from=1, to=11)
curve((-138.4587 + 280.0303) + (6.7429 - 12.8373)*x, add=T, from=16, to=21)
curve(-138.4587 + 6.7429*x,, add=T, from=24, to=max(x))
abline(v=16, lty=2)
abline(v=24, lty=2)
```

```{r}
library(segmented)
lin.mod <- lm(y~x) 
segmented.mod <- segmented(lin.mod, seg.Z = ~x, psi= c(16, 24))
summary(segmented.mod)
```

```{r}
x <- 15
yhat_pred = 3.612 + 5.198 * x - 11.292 * (x - 12.217)
yhat_pred
```

# NOMOR 3
```{r}
# Load Data
data<-read.csv("C:/Users/BiliL/Downloads/Project Coding GitHub/Praktikum_ART/applied-regression-analysis/data/Dataset Responsi Bagian 3.csv",header=TRUE)
data
```

```{r}
#Spline Linear Truncated 1 Titik Knot
GCV1=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  aa=rep(1,N)
  data1=matrix(ncol=m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot1)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:nk1)
  {
    for (j in 1:m)
    {
      for (k in 1:N)
      {
        if(data[k,(j+para+1)]<knot1[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(j+para+1)]-knot1[i,j]
      }
    }
    mx=as.matrix(cbind(aa,data2,data1))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot1))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 1 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot1[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot1[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=1)
  datagcv1=matrix(ncol=m,nrow=N)
  for (j in 1:m)
  {
    for (k in 1:N)
    {
      if (data[k,(j+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(j+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2,datagcv1))
  
  list(knotgcv=knotgcv1,mingcv=mingcv,mxgcv=mxgcv)
}

GCV1(data)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#Regresi Nonparametrik Spline Truncated 1 Titik Knot (Linear)
#Estimasi Parameter

estimasi=function(data, mx, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mx)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit)<-"thitung"
  colnames(B)<-"parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=", sqrt(MSE), "Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=", pvalue,"\n")
  yy=cbind(yhat, res)
  list(res=res, yhat=yhat, Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV1(data)$mxgcv, 0.05, 'gcv')  #Koefisien Determinasinya adalah sebesar 34.66%

prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```{r}
#Spline Kuadratik Truncated 1 Titik Knot
GCV1=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  aa=rep(1,N)
  data1=matrix(ncol=m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot1)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:nk1)
  {
    for (j in 1:m)
    {
      for (k in 1:N)
      {
        if(data[k,(j+para+1)]<knot1[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(j+para+1)]-knot1[i,j]
      }
    }
    mx=as.matrix(cbind(aa,data2,(data2^2),(data1^2)))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot1))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 1 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot1[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot1[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=1)
  datagcv1=matrix(ncol=m,nrow=N)
  for (j in 1:m)
  {
    for (k in 1:N)
    {
      if (data[k,(j+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(j+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2,(data2^2),(datagcv1^2)))
  
  list(knotgcv=knotgcv1,mingcv=mingcv,mxgcv=mxgcv)
}

GCV1(data)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#Regresi Nonparametrik Spline Truncated 1 Titik Knot (Kuadratik)
#Estimasi Parameter


estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit)<-"thitung"
  colnames(B)<-"parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=",sqrt(MSE),"Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=",pvalue,"\n")
  yy=cbind(yhat,res)
  list(res=res,yhat=yhat,Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV1(data)$mxgcv, 0.05, 'gcv')  #Koefisien Determinasinya adalah sebesar 40.82%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```


```{r}
#Spline Kubik Truncated 1 Titik Knot
GCV1=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  aa=rep(1,N)
  data1=matrix(ncol=m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot1)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:nk1)
  {
    for (j in 1:m)
    {
      for (k in 1:N)
      {
        if(data[k,(j+para+1)]<knot1[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(j+para+1)]-knot1[i,j]
      }
    }
    mx=as.matrix(cbind(aa,data2,(data2^2),(data2^3),(data1^3)))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot1))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 1 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot1[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot1[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=1)
  datagcv1=matrix(ncol=m,nrow=N)
  for (j in 1:m)
  {
    for (k in 1:N)
    {
      if (data[k,(j+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(j+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2,(data2^2),(data2^3),(datagcv1^3)))
  
  list(knotgcv=knotgcv1,mingcv=mingcv,mxgcv=mxgcv)
}

GCV1(data)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#Regresi Nonparametrik Spline Truncated 1 Titik Knot (Kubik)
#Estimasi Parameter


estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit)<-"thitung"
  colnames(B)<-"parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=",sqrt(MSE),"Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=", pvalue, "\n")
  yy=cbind(yhat, res)
  list(res=res, yhat=yhat, Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV1(data)$mxgcv, 0.05, 'gcv')  #Koefisien Determinasinya adalah sebesar 39.00%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```{r}
# KNOT 2 Linear
GCV2=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  a2=nk-2
  z=(a2*(a2-1)/2)
  knot2=cbind(rep(NA,(z+1)))
  for (i in (1:m))
  {
    knot=rbind(rep(NA,2))
    for (j in 1:(a2-1))
    {
      for (k in (j+1):a2)
      {
        xx=cbind(knot1[j,i],knot1[k,i])
        knot=rbind(knot,xx)
      }
    }
    knot2=cbind(knot2,knot)
  }
  knot2=knot2[2:(z+1),2:(2*m+1)]  
  a3=nrow(knot2)
  aa=rep(1,N)
  data1=matrix(ncol=2*m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot2)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:a3)
  {
    for (j in 1:(2*m))
    {
      if (mod(j,2)==1) b=floor(j/2)+1 else b=j/2
      for (k in 1:N)
      {
        if(data[k,(b+para+1)]<knot2[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(b+para+1)]-knot2[i,j]
      }
    }
    
    mx=as.matrix(cbind(aa,data2,data1))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot2))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 2 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot2[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot2[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=2)
  datagcv1=matrix(ncol=2*m,nrow=N)
  for (j in 1:(2*m))
  {
    if(mod(j,2)==1) b=floor(j/2)+1 else b=j/2
    for (k in 1:N)
    {
      if (data[k,(b+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(b+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2,datagcv1))
 
  
  list(knotgcv=knotgcv1,mingcv=mingcv,mxgcv=mxgcv)
}

GCV2(data) 

#Regresi Nonparametrik Spline Truncated 2 Titik Knot (Linear)
#Estimasi Parameter

estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit)<-"thitung"
  colnames(B)<-"parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=",sqrt(MSE),"Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=",pvalue,"\n")
  yy=cbind(yhat,res)
  list(res=res,yhat=yhat,Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV2(data)$mxgcv, 0.05, 'gcv') #Koefisien Determinasi sebesar 68.53%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

```{r}
# Knot 2 Kuadrat
GCV2=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  a2=nk-2
  z=(a2*(a2-1)/2)
  knot2=cbind(rep(NA,(z+1)))
  for (i in (1:m))
  {
    knot=rbind(rep(NA,2))
    for (j in 1:(a2-1))
    {
      for (k in (j+1):a2)
      {
        xx=cbind(knot1[j,i],knot1[k,i])
        knot=rbind(knot,xx)
      }
    }
    knot2=cbind(knot2,knot)
  }
  knot2=knot2[2:(z+1),2:(2*m+1)]  
  a3=nrow(knot2)
  aa=rep(1,N)
  data1=matrix(ncol=2*m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot2)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:a3)
  {
    for (j in 1:(2*m))
    {
      if (mod(j,2)==1) b=floor(j/2)+1 else b=j/2
      for (k in 1:N)
      {
        if(data[k,(b+para+1)]<knot2[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(b+para+1)]-knot2[i,j]
      }
    }
    
    mx=as.matrix(cbind(aa,data2,(data2^2),(data1^2)))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot2))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 2 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot2[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot2[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=2)
  datagcv1=matrix(ncol=2*m,nrow=N)
  for (j in 1:(2*m))
  {
    if(mod(j,2)==1) b=floor(j/2)+1 else b=j/2
    for (k in 1:N)
    {
      if (data[k,(b+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(b+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2,(data2^2),(datagcv1^2)))
  
  
  list(knotgcv=knotgcv1,mingcv=mingcv,mxgcv=mxgcv)
}

GCV2(data) 

#Regresi Nonparametrik Spline Truncated 2 Titik Knot (Kuadratik)
#Estimasi Parameter

estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit)<-"thitung"
  colnames(B)<-"parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=", sqrt(MSE), "Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=", pvalue,"\n")
  yy=cbind(yhat, res)
  list(res=res, yhat=yhat, Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV2(data)$mxgcv, 0.05, 'gcv') #Koefisien Determinasi sebesar 63.19%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```{r}
# Knot 2 Kubik
GCV2=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  a2=nk-2
  z=(a2*(a2-1)/2)
  knot2=cbind(rep(NA,(z+1)))
  for (i in (1:m))
  {
    knot=rbind(rep(NA,2))
    for (j in 1:(a2-1))
    {
      for (k in (j+1):a2)
      {
        xx=cbind(knot1[j,i],knot1[k,i])
        knot=rbind(knot,xx)
      }
    }
    knot2=cbind(knot2,knot)
  }
  knot2=knot2[2:(z+1),2:(2*m+1)]  
  a3=nrow(knot2)
  aa=rep(1,N)
  data1=matrix(ncol=2*m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot2)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:a3)
  {
    for (j in 1:(2*m))
    {
      if (mod(j,2)==1) b=floor(j/2)+1 else b=j/2
      for (k in 1:N)
      {
        if(data[k,(b+para+1)]<knot2[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(b+para+1)]-knot2[i,j]
      }
    }
    
    mx=as.matrix(cbind(aa,data2,(data2^2),(data2^3),(data1^3)))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot2))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 2 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot2[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot2[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=2)
  datagcv1=matrix(ncol=2*m,nrow=N)
  for (j in 1:(2*m))
  {
    if(mod(j,2)==1) b=floor(j/2)+1 else b=j/2
    for (k in 1:N)
    {
      if (data[k,(b+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(b+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2,(data2^2),(data2^3),(datagcv1^3)))
  
  
  list(knotgcv=knotgcv1,mingcv=mingcv,mxgcv=mxgcv)
}

GCV2(data) 

#Regresi Nonparametrik Spline Truncated 2 Titik Knot (Kubik)
#Estimasi Parameter

estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit)<-"thitung"
  colnames(B)<-"parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=",sqrt(MSE),"Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=",pvalue,"\n")
  yy=cbind(yhat,res)
  list(res=res,yhat=yhat,Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV2(data)$mxgcv, 0.05, 'gcv') #Koefisien Determinasi sebesar 64.31%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```{r}
# Knot 3 Linear
GCV3=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  a2=nk-2
  z=(a2*(a2-1)*(a2-2)/6)
  knot2=cbind(rep(NA,(z+1)))
  for (i in (1:m))
  {
    knot=rbind(rep(NA,3))
    for (j in 1:(a2-2))
    {
      for (k in (j+1):(a2-1))
      {
        for (g in (k+1):a2)
        {
          xx=cbind(knot1[j,i],knot1[k,i],knot1[g,i])
          knot=rbind(knot,xx)
        }
      }
    }
    knot2=cbind(knot2,knot)
  }
  knot2=knot2[2:(z+1),2:(3*m+1)]  
  a3=nrow(knot2)
  aa=rep(1,N)
  data1=matrix(ncol=3*m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot2)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:a3)
  {
    for (j in 1:(3*m))
    {
      b=ceiling(j/3)
      for (k in 1:N)
      {
        if(data[k,(b+para+1)]<knot2[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(b+para+1)]-knot2[i,j]
      }
    }
    
    mx=as.matrix(cbind(aa,data2,data1))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot2))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 3 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot2[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot2[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=3)
  datagcv1=matrix(ncol=3*m,nrow=N)
  for (j in 1:(3*m))
  {
    b=ceiling(j/3)
    for (k in 1:N)
    {
      if (data[k,(b+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(b+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2,datagcv1))
  
  list(knotgcv=knotgcv1,mingcv=mingcv,mxgcv=mxgcv)
}

GCV3(data)

#Regresi Nonparametrik Spline Truncated 3 Titik Knot (Linear)
#Estimasi Parameter

estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit)<-"thitung"
  colnames(B)<-"parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=", sqrt(MSE), "Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=", pvalue,"\n")
  yy=cbind(yhat, res)
  list(res=res, yhat=yhat, Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV3(data)$mxgcv, 0.05, 'gcv') #Koefisien Determinasi sebesar 76.70%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

```

```{r}
# Knot 3 Kuadrat
GCV3=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  a2=nk-2
  z=(a2*(a2-1)*(a2-2)/6)
  knot2=cbind(rep(NA,(z+1)))
  for (i in (1:m))
  {
    knot=rbind(rep(NA,3))
    for (j in 1:(a2-2))
    {
      for (k in (j+1):(a2-1))
      {
        for (g in (k+1):a2)
        {
          xx=cbind(knot1[j,i],knot1[k,i],knot1[g,i])
          knot=rbind(knot,xx)
        }
      }
    }
    knot2=cbind(knot2,knot)
  }
  knot2=knot2[2:(z+1),2:(3*m+1)]  
  a3=nrow(knot2)
  aa=rep(1,N)
  data1=matrix(ncol=3*m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot2)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:a3)
  {
    for (j in 1:(3*m))
    {
      b=ceiling(j/3)
      for (k in 1:N)
      {
        if(data[k,(b+para+1)]<knot2[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(b+para+1)]-knot2[i,j]
      }
    }
    
    mx=as.matrix(cbind(aa, data2, (data2^2), (data1^2)))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV,Koef.Determinasi,MSE,knotke,knot2))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 3 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot2[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot2[dataG[1,4],])
  knotgcv1=matrix(knotgcv,nrow=3)
  datagcv1=matrix(ncol=3*m,nrow=N)
  for (j in 1:(3*m))
  {
    b=ceiling(j/3)
    for (k in 1:N)
    {
      if (data[k, (b+para+1)] < knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k, (b+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa,data2, (data2^2), (datagcv1^2)))
  
  list(knotgcv=knotgcv1, mingcv=mingcv, mxgcv=mxgcv)
}

GCV3(data)

#Regresi Nonparametrik Spline Truncated 3 Titik Knot (Kuadratik)
#Estimasi Parameter

estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit, (n1-1), (n-n1), lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]), (n-n1), lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit) <- "thitung"
  colnames(B) <- "parameter untuk Beta"
  
  tg1=cbind(B, thit, pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=", sqrt(MSE), "Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=", pvalue,"\n")
  yy=cbind(yhat, res)
  list(res=res, yhat=yhat, Koef.Determinasi=Koef.Determinasi)
}

model_truncated=estimasi(data, GCV3(data)$mxgcv, 0.05, 'gcv') #Koefisien Determinasi sebesar 77.59%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

```

```{r}
# Knot 3 Kubik
GCV3=function(data)
{
  library(Matrix)
  library(pracma)
  para=0
  data=as.matrix(data)
  N=length(data[,1]) #Banyaknya Observasi
  M=2 #Banyaknya Kolom 
  m=ncol(data)-para-1  #m=banyaknya variabel nonparametrik
  dataA=data[,(para+2):M]
  dataA=as.matrix(dataA)
  F=diag(N)
  nk=22 #Banyaknya alternatif titik knot yg akan dicoba
  knot1=matrix(ncol=m,nrow=nk)
  for (i in (1:m)) #Membuat knot
  {
    a=seq(min(dataA[,i]),max(dataA[,i]),length.out=nk)
    knot1[,i]=t(as.matrix(a))
  }
  a1=length(knot1[,1])
  knot1=as.matrix(knot1[2:(a1-1),])
  a2=nk-2
  z=(a2*(a2-1)*(a2-2)/6)
  knot2=cbind(rep(NA,(z+1)))
  for (i in (1:m))
  {
    knot=rbind(rep(NA,3))
    for (j in 1:(a2-2))
    {
      for (k in (j+1):(a2-1))
      {
        for (g in (k+1):a2)
        {
          xx=cbind(knot1[j,i],knot1[k,i],knot1[g,i])
          knot=rbind(knot,xx)
        }
      }
    }
    knot2=cbind(knot2,knot)
  }
  knot2=knot2[2:(z+1),2:(3*m+1)]  
  a3=nrow(knot2)
  aa=rep(1,N)
  data1=matrix(ncol=3*m,nrow=N)
  data2=data[,2:M] #Data yang variabel X saja
  nk1=nrow(knot2)
  GCV=as.matrix(rep(NA,nk1),ncol=1);colnames(GCV)<-"GCV"
  MSE=as.matrix(rep(NA,nk1),ncol=1);colnames(MSE)<-"MSE"
  SSE=rep(NA,nk1)
  SST=rep(NA,nk1)
  SSR=rep(NA,nk1)
  Koef.Determinasi=as.matrix(rep(NA,nk1),ncol=1);colnames(Koef.Determinasi)<-"Koef.Determinasi"
  knotke=matrix(c(1:nk1),ncol=1);colnames(knotke)<-"knot_ke"
  for (i in 1:a3)
  {
    for (j in 1:(3*m))
    {
      b=ceiling(j/3)
      for (k in 1:N)
      {
        if(data[k,(b+para+1)]<knot2[i,j]) data1[k,j]=0 else data1[k,j]=data[k,(b+para+1)]-knot2[i,j]
      }
    }
    
    mx=as.matrix(cbind(aa,data2,(data2^2),(data2^3),(data1^3)))
    C=pinv(t(mx)%*%mx)
    B=C%*%(t(mx)%*%data[,1])
    ypred=mx%*%B
    residual=data[,1]-ypred
    SSE[i]=sum((residual)^2)
    SSR[i]=sum((ypred-mean(data[,1]))^2)
    SST[i]=sum((data[,1]-mean(data[,1]))^2)
    MSE[i]=SSE[i]/(N)
    Koef.Determinasi[i]=(SSR[i]/(SSR[i]+SSE[i]))
    A=mx%*%C%*%t(mx)
    A1=(F-A)
    A2=(sum(diag(A1))/N)^2
    GCV[i]=MSE[i]/A2
    
  }
  dataAll=as.matrix(cbind(GCV, Koef.Determinasi, MSE, knotke, knot2))
  dataG=dataAll[order(GCV),]
  
  cat("====================================================================================================================","\n")
  cat("HASIL GCV terkecil dengan 3 titik knot","\n")
  cat("====================================================================================================================","\n")
  print(((dataG[1,1:4])))
  cat("Dengan titik Knot","\n")
  print((knot2[dataG[1,4],]))
  cat("Nilai GCV 10 terkecil pertama","\n")
  print(dataG[1:10,])
  cat("\n")
  cat("====================================================================================================================","\n")
  mingcv=dataG[1,1]
  knotgcv=as.matrix(knot2[dataG[1,4],])
  knotgcv1=matrix(knotgcv, nrow=3)
  datagcv1=matrix(ncol=3*m, nrow=N)
  for (j in 1:(3*m))
  {
    b=ceiling(j/3)
    for (k in 1:N)
    {
      if (data[k,(b+para+1)]<knotgcv[j,1]) datagcv1[k,j]=0 else
        datagcv1[k,j]=data[k,(b+para+1)]-knotgcv[j,1]
    }
  }
  mxgcv=as.matrix(cbind(aa, data2, (data2^2), (data2^3), (datagcv1^3)))
  
  list(knotgcv=knotgcv1, mingcv=mingcv, mxgcv=mxgcv)
}

GCV3(data)

#Regresi Nonparametrik Spline Truncated 3 Titik Knot (Kubik)
#Estimasi Parameter

estimasi=function(data, mxgcv, alpha, type)
{
  data=as.matrix(data)
  n=nrow(data)
  mx=as.matrix(mxgcv)
  C=pinv(t(mx)%*%mx)
  B=C%*%(t(mx)%*%data[,1])
  cat("\n")
  cat("\n")
  cat("====================================================================================================================","\n")
  cat("hasil estimasi parameter","\n")
  cat("====================================================================================================================","\n")
  n1=nrow(B)
  yhat=mx%*%B
  res=data[,1]-yhat
  SSE=sum((res)^2)
  SSR=sum((yhat-mean(data[,1]))^2)
  SST=sum((data[,1]-mean(data[,1]))^2)
  MSE=SSE/(n)
  Koef.Determinasi=(SSR/(SSR+SSE))*100
  MSR=SSR/(n1-1)
  
  #Uji Simultan
  Fhit=MSR/MSE
  pvalue=pf(Fhit,(n1-1),(n-n1),lower.tail=FALSE)
  
  #Uji Parsial
  thit=rep(NA,n1)
  pvaluee=rep(NA,n1)
  MSE=as.numeric(MSE)
  SE=sqrt(diag(MSE*(pinv(t(mx)%*%mx))))
  for (i in 1:n1)
  {
    thit[i]=B[i,1]/SE[i]
    pvaluee[i]=2*(pt(abs(thit[i]),(n-n1),lower.tail=FALSE))
  }
  thit=as.matrix(thit)
  colnames(thit) <- "thitung"
  colnames(B) <- "parameter untuk Beta"
  
  tg1=cbind(B,thit,pvaluee)
  cat("====================================================================================================================","\n")
  cat("Estimasi Parameter","\n")
  cat("====================================================================================================================","\n")
  print(tg1)
  cat("\n")
  cat("Analysis of Variance","\n")
  cat("====================================================================================================================","\n")
  cat("Sumber  ","df","\t","SS","\t","\t","MS","\t","\t","Fhit","\n")
  cat("Regresi",(n1-1),"\t",SSR,"\t",MSR,"\t",Fhit,"\n")
  cat("Error  ",n-n1,"\t",SSE,"\t",MSE,"\n")
  cat("Total  ",n-n1,"\t",SST,"\n")
  cat("====================================================================================================================","\n")
  cat("s=", sqrt(MSE), "Rsq=", Koef.Determinasi,"\n")
  cat("pvalue(F)=",pvalue,"\n")
  yy=cbind(yhat, res)
  list(res=res, yhat=yhat, Koef.Determinasi=Koef.Determinasi)
}

model_truncated = estimasi(data, GCV3(data)$mxgcv, 0.05, 'gcv') #Koefisien Determinasi sebesar 76.59%
prediksi <- model_truncated$yhat
plot(data$x, data$y)
lines(data$x, prediksi, col="red")

```

```{r}
# Pred 1
pred1 = 57.078 - (9.922*16.3) + (0.267*(16.3^2))
pred1
```

```{r}
# pred 2
pred2 = 57.078 - (9.922*22.8) + (0.267*(22.8^2)) - (3.577*(22.8 - 17.971)^2) + (8.250*(22.8 - 20.772)^2)
pred2
```

