---
title: "Tugas 1 Praktikum Analisis Regresi Terapan"
author: "Cheisa Billy Putra Antoni"
date: "2026-03-21"
output: html_document
---

# SOAL NOMOR 1
```{r}
# Load Dataset 1
library(readxl)
df1 = read_xlsx("C:/Users/BiliL/Downloads/Project Coding GitHub/Praktikum_ART/applied-regression-analysis/data/Dataset Nomor 1 - Tugas 1.xlsx")
head(df1)
```

```{r}
# Deklarasi Variabel
x = df1$Followers
y = df1$Engagement_Rate
```

```{r fig.width = 12, fig.height = 6}
# Asumsi Linearitas 
plot(x, y, main = "Scatterplot Uji Linearitas",
     xlab = "Jumlah Followers", ylab = "Persentase Interaksi", pch = 19)
abline(lm(y ~ x), col = "blue")

model1 = lm(formula = y ~ x, data = df1)
summary(model1)$r.squared
```

```{r}
# Pembentukan Model
model1 = lm(formula = y ~ x, data = df1)
cat("Nilai Korelasi (R) = ", cor(x, y))
cat("\n")
summary(model1)
```

```{r fig.width = 12, fig.height = 6}
# Diagnostic Checking Linearitas
plot(x, y, main = "Scatterplot Uji Linearitas Model 1",
     xlab = "Jumlah Followers", ylab = "Persentase Interaksi", pch = 19)
abline(lm(y ~ x), col = "blue")
```

```{r fig.width = 12, fig.height = 6}
# Diagnostic Checking Normalitas Residual
res1 = model1$residual
hist(res1, main = "Histogram Residual Model 1", 
     xlab = "Residual", ylab = "Frekuensi", col = "skyblue")

qqnorm(res1, main = "Normal Q-Q Plot Residual Model 1")
qqline(res1)

library(nortest)
lillie.test(res1)
```

```{r fig.width = 12, fig.height = 6}
# Diagnostic Checking Homoskedastisitas
plot(model1, 1)

library(lmtest)
bptest(model1)
```

```{r}
# Diagnostic Checking Autokorelasi
library(car)
durbinWatsonTest(model1)
```

```{r}
# Data Testing
x_test = data.frame(x = c(1876, 6261, 5712, 3764, 8126))
y_test = c(8.17, 6.63, 6.88, 7.58, 6.45)
y_pred = predict(model1, newdata = x_test)
```

```{r}
# Mean Squared Error (MSE)
mse = mean((y_test - y_pred)^2)
cat("Mean Squared Error = ", mse)
```

# SOAL NOMOR 2
```{r}
# Load Dataset 2
library(readxl)
df2 = read_xlsx("C:/Users/BiliL/Downloads/Project Coding GitHub/Praktikum_ART/applied-regression-analysis/data/Dataset Nomor 2 & 3 - Tugas 1.xlsx")
head(df2)
```

```{r}
# Unique Values
unique(df2$content_type)
```

```{r}
# Variabel Dummy
df2$content_type_Stories = ifelse(df2$content_type == "Stories", 1, 0)
df2$content_type_Photo = ifelse(df2$content_type == "Photo", 1, 0)
df2$content_type_Video = ifelse(df2$content_type == "Video", 1, 0)
head(df2, 10)
```

```{r}
# Build Functions
# Model Criterion Function
library(olsrr)
model_criterion <- function(data, model){
  rss <- sum(model$residuals^2)
  n <- nrow(data)
  k <- length(coef(model))
  sigma2_hat <- rss/(n - k)
  # Menghitung kriteria pemilihan model terbaik
  aic <- n*log(rss/n) + 2*k
  sbc <- n*log(rss/n) + k*log(n)
  cp <- (rss/sigma2_hat) - n + 2*k
  press <- ols_press(model)
  r <- sqrt(summary(model)$r.square)
  r.square <- summary(model)$r.square
  adj.r.square <- summary(model)$adj.r.square
  se <- summary(model)$sigma
  # Membuat data frame hasil kriteria model
  result <- data.frame(R=r, R.Square=r.square, "Adj.RSquare"=adj.r.square,"Residual Standard Error"=se ,AIC=aic, SBC=sbc, CP_Mallows=cp, PRESS=press)
  print("Model Criterion for Model:")
  return(result)
}
```

```{r}
# Model 1
df2_model = df2[, -5]
model1 = lm(engagement_rate ~ ., data = df2_model)
summary(model1)
model_criterion(df2_model,model1)
```

```{r}
# Model 2 (Drop caption_len)
library(dplyr)
df2_model = select(df2_model, -caption_len)
model2 = lm(engagement_rate ~ ., data = df2_model)
summary(model2)
model_criterion(df2_model,model2)
```

```{r}
# Model 3 (Drop content_type)
df2_model = select(df2_model, -c(content_type_Stories, content_type_Photo, content_type_Video))
model3 = lm(engagement_rate ~ ., data = df2_model)
summary(model3)
model_criterion(df2_model,model3)
```

```{r}
# Model 4 (Drop video_ratio)
df2_model = select(df2_model, -video_ratio)
model4 = lm(engagement_rate ~ ., data = df2_model)
summary(model4)
model_criterion(df2_model,model4)
```

```{r}
# Model 5 (Drop story_freq)
df2_model = select(df2_model, -story_freq)
model5 = lm(engagement_rate ~ ., data = df2_model)
summary(model5)
model_criterion(df2_model,model5)
```

```{r}
# Model 6 (Drop post_hour)
df2_model = select(df2_model, -post_hour)
model6 = lm(engagement_rate ~ ., data = df2_model)
summary(model6)
model_criterion(df2_model,model6)
```

```{r}
# Uji Kelayakan (Overall Test) Untuk Model 6
overall_p <- function(my_model) {
  f <- summary(my_model)$fstatistic
  p <- pf(f[1],f[2],f[3],lower.tail=F)
  attributes(p) <- NULL
  return(p)
}

overall_test = data.frame(matrix(ncol = 2, nrow = 1))
colnames(overall_test) = c("Model", "Overall Test's P-Value")
overall_test$Model = c("Model 6")
overall_test$P.Value = c(overall_p(model6))
print(overall_test[,-2])
```

# SOAL NOMOR 3
```{r}
# Data Testing
data_test = data.frame(
  post_freq = 5,
  followers = 12000,
  active_months = 36,
  avg_hashtags = 9,
  post_hour = 18,
  story_freq = 10,
  video_ratio = 0.20,
  content_type_Stories = 0,
  content_type_Photo = 0,
  content_type_Video = 1)

y_pred = predict(model2, newdata = data_test)
y_pred
```

