---
title: "Praktikum_ART"
author: "Cheisa Billy Putra Antoni"
date: "2026-02-25"
output: html_document
---

# PERTEMUAN 1 & 2
## REGRESI LINEAR SEDERHANA MULAI DARI UJI ASUMSI, INTERFERENSIAL MODEL, DAN DIAGNOSTIC CHECKING
```{r}
# Load Dataset
library(openxlsx)
df <- read.xlsx(
  "C:\\Users\\BiliL\\Downloads\\Project Coding GitHub\\
  Praktikum_ART\\applied-regression-analysis\\data\\
  Pertemuan 1 - Dataset.xlsx", sheet = 1
)
head(df)
```

```{r}
# Asumsi Linearitas Pakai Scatter Plot
x <- df$Suhu_Ruangan
y <- df$Cacat_Produksi
plot(x, y, main = "Scatter Plot Linearitas",
  ylab = "Jumlah Cacat Produksi",
  xlab = "Rata-rata Suhu Ruangan", pch = 19
)

# Garis Fit Dengan Intercept
abline(lm(y ~ x), col = "blue")

# Garis Fit Tanpa Intercept
abline(lm(y ~ x - 1), col = "red")
```

```{r}
# Nilai R-Square Dengan Intercept
model1 <- lm(formula = y ~ x, data = df)
summary(model1)$r.squared

# Nilai R-Square Tanpa Intercept
model2 <- lm(formula = y ~ x - 1, data = df)
summary(model2)$r.squared
```

```{r}
# Summary Model
summary(model1)
summary(model2)
```

```{r}
# Normalitas Error Pakai Histogram
hist(model1$residual, main = "Histogram Residual",
  xlab = "Residual", ylab = "Frekuensi", col = "lightblue"
)

# Normalitas Error Pakai Q-Q Plot
qqnorm(model1$residual, main = "Normal Q-Q Plot Residual")
qqline(model1$residual)

# Normalitas Error Pakai Shapiro Test
shapiro.test(model1$residual)
```

```{r}
# Homoskedastisitas Error
plot(model1, 1)
library(lmtest)
bptest(model1)
```

```{r}
# Autokorelasi Error
library(car)
durbinWatsonTest(model1)
dwtest(model1)
```

# PERTEMUAN 3
```{r}
# Soon
```