---
title: "Praktikum Analisis Regresi Terapan"
author: "Cheisa Billy Putra Antoni"
date: "2026-02-25"
output: html_document
---

# PERTEMUAN 1 & 2: REGRESI LINEAR SEDERHANA MULAI DARI UJI ASUMSI, INTERFERENSIAL MODEL, DAN DIAGNOSTIC CHECKING
```{r}
# Load Dataset
library(openxlsx)
df = read.xlsx(
"C:\\Users\\BiliL\\Downloads\\Project Coding GitHub\\Praktikum_ART\\applied-regression-analysis\\data\\Pertemuan 1 - Dataset.xlsx", sheet = 1
)
head(df)
```

```{r}
# Asumsi Linearitas Pakai Scatter Plot
x = df$Suhu_Ruangan
y = df$Cacat_Produksi
plot(x, y, main = "Scatter Plot Linearitas",
  ylab = "Jumlah Cacat Produksi",
  xlab = "Rata-rata Suhu Ruangan", pch = 19
)

# Garis Fit Dengan Intercept
abline(lm(y ~ x), col = "blue")

# Garis Fit Tanpa Intercept
abline(lm(y ~ x - 1), col = "red")
```

```{r}
# Nilai R-Square Dengan Intercept
model1 = lm(formula = y ~ x, data = df)
summary(model1)$r.squared

# Nilai R-Square Tanpa Intercept
model2 = lm(formula = y ~ x - 1, data = df)
summary(model2)$r.squared
```

```{r}
# Mean Dari Y Hat (Model Dengan Intercept)
mean(fitted.values(model1))

# Mean Dari Y Hat (Model Tanpa Intercept)
mean(fitted.values(model2))

# Mean Dari Y
mean(y)

# Mean Dari X
mean(x)
```

```{r}
# Mean Residual (Dengan Intercept)
mean(residuals(model1))

# Mean Residual (Tanpa Intercept)
mean(residuals(model2))
```


```{r}
# Summary Model
summary(model1)
summary(model2)
```

```{r}
# Normalitas Error Pakai Histogram
hist(model1$residual, main = "Histogram Residual",
  xlab = "Residual", ylab = "Frekuensi", col = "lightblue"
)

# Normalitas Error Pakai Q-Q Plot
qqnorm(model1$residual, main = "Normal Q-Q Plot Residual")
qqline(model1$residual)

# Normalitas Error Pakai Shapiro Test
shapiro.test(model1$residual)
```

```{r}
# Homoskedastisitas Error
plot(model1, 1)
library(lmtest)
bptest(model1)
```

```{r}
# Autokorelasi Error
library(car)
durbinWatsonTest(model1)

# Autokorelasi Error (Lebih Singkat)
dwtest(model1)
```

#PERTEMUAN 3: REGRESI LINEAR BERGANDA & DUMMY VARIABLE
```{r}
# Load Dataset
library(openxlsx)
df3 = read.xlsx("C:\\Users\\BiliL\\Downloads\\Project Coding GitHub\\Praktikum_ART\\applied-regression-analysis\\data\\Pertemuan 3 - Dataset.xlsx", sheet = 1)
df3
```

```{r}
# Variabel Unik
unique(df3$Sex)

# Variabel Independen
y = df3$Whole.weight

# Variabel Dependen (Ambil Data Frame Selain Whole Weight [-5])
x = df3[, -5]
```

```{r}
# Asumsi Linearitas (Matriks Scatterplot)
pairs(df3[,-1], main = "Matriks Scatterplot Data Numerik Abalone", pch = 19)
```

```{r}
# Nilai R-Square
x_num = x[,-1]
r2 = data.frame(matrix(ncol = ncol(x_num), nrow = 1))
colnames(r2) = colnames(x_num)
for (i in 1:ncol(x_num)){
  r2[i] = summary(lm(y ~ x_num[,i]))$r.squared
}
print(r2)
```

```{r}
# Dummy Variable (One Hot Encoding) Dengan Remove First Dummy
library(fastDummies)
df3 = dummy_cols(df3, select_columns = "Sex", remove_first_dummy = TRUE)
df3
```

```{r}
# Model Rege=resi (Metode Backward)
model0 = lm(Whole.weight ~ ., data = df3[,-1])
model_backward = step(model0, direction = "backward")
summary(model_backward)
```

```{r}
# Model Regresi Metode Enter (Model 1)
df3_modelling <- df3[,-1]
model1 = lm(Whole.weight ~ ., data = df3_modelling)
summary(model1)
sqrt(summary(model1)$r.squared)
```

```{r}
# Model 2 (Drop Rings)
library(dplyr)
df3_modelling <- select(df3_modelling, -Rings)
model2 = lm(Whole.weight ~ ., data = df3_modelling)
summary(model2)
sqrt(summary(model2)$r.squared)
```

```{r}
# Model 3 (Drop Length)
df3_modelling <- select(df3_modelling, -Length)
model3 = lm(Whole.weight ~ ., data = df3_modelling)
summary(model3)
sqrt(summary(model3)$r.squared)
```

```{r}
# Model 4 (Drop Sex)
df3_modelling <- select(df3_modelling, -c(Sex_Infant, Sex_Male))
model4 = lm(Whole.weight ~ ., data = df3_modelling)
summary(model4)
sqrt(summary(model4)$r.squared)
```

```{r}
# Model 5 (Drop Height)
df3_modelling <- select(df3_modelling, -Height)
model5 = lm(Whole.weight ~ ., data = df3_modelling)
summary(model5)
sqrt(summary(model5)$r.squared)
```

```{r}
# Model 6 (Drop Diameter)
df3_modelling <- select(df3_modelling, -Diameter)
model6 = lm(Whole.weight ~ ., data = df3_modelling)
summary(model6)
sqrt(summary(model6)$r.squared)
```

# PERTEMUAN 6 SELEKSI SEKUENSIAL
```{r}
# Load Dataset
library(openxlsx)
df6 = read.xlsx(
"C:\\Users\\BiliL\\Downloads\\Project Coding GitHub\\Praktikum_ART\\applied-regression-analysis\\data\\Pertemuan 6 - Dataset.xlsx")
head(df6)
```

```{r}
# Membuat Base Model
baseModel = lm(BCM ~ 1, df6)
model <- lm(BCM ~ ., data = df6)
baseModel
model
```


```{r}
# Metode Forward (Tanpa Library)
step(baseModel, scope = list(upper = model, lower = ~ 1), direction = "forward")
```

```{r}
# Metode Backward (Tanpa Library)
step(model, direction = "backward")
```

```{r}
# All Possible Regression
library(olsrr)
ols_step_all_possible(model)
```

```{r}
# Metode Forward (Dengan Library)
# Stepwise Forward Selection berdasarkan p-value
ols_step_forward_p(model)
```


```{r}
# Metode Backward (Dengan Library)
# Stepwise Backward Selection berdasarkan p-value
ols_step_backward_p(model)
```


```{r}
# Metode Stepwise (Dengan Library)
# Stepwise Regression berdasarkan p-value
ols_step_both_p(model)
```

# PERTEMUAN 7 REGRESI POLINOMIAL
```{r}
# Load Dataset
library(openxlsx)
df7_1 = read.xlsx(
"C:\\Users\\BiliL\\Downloads\\Project Coding GitHub\\Praktikum_ART\\applied-regression-analysis\\data\\Pertemuan 7 - Dataset.xlsx", sheet = 1)
head(df7_1)

df7_2 = read.xlsx(
"C:\\Users\\BiliL\\Downloads\\Project Coding GitHub\\Praktikum_ART\\applied-regression-analysis\\data\\Pertemuan 7 - Dataset.xlsx", sheet = 2)
head(df7_2)
```

```{r}
# Variabel Dependen
Y = df7_1$Nilai.Try.Out
# Variabel Independen
X = df7_1$Lama.Belajar
```

```{r}
# Scatter Plot
plot(X, Y, main="Scatterplot Uji Linearitas",
     xlab="Lama Belajar", ylab="Nilai Try Out", pch=19)
abline(lm(Y~X), col="blue")
```

```{r}
# Pembentukan Model
poly2 = lm(Y ~ poly(X, 2, raw = TRUE))
summary(poly2)
sqrt(summary(poly2)$r.squared)
```

```{r}
# Visualisasi Model
pred2 = predict(poly2, newdata = list(x=X))
plot(X, Y, main="Degree-2 Polynomial",
     xlab="Study Hours", ylab="Exam Scores", pch=19)
lines(X, pred2, lwd = 2, col = "red")  
```

```{r}
# Variabel Dependen
Y = df7_2$Tensile.Strength
# Variabel Independen
X = df7_2$Hardwood.Concentration
```

```{r}
# Scatter Plot 
plot(X, Y, main="Scatterplot Uji Linearitas",
     xlab="Hardwood Concentration", ylab="Tensile Strength", pch=19)
abline(lm(Y~X), col="blue")
```

```{r}
# Pembentukan Model
## Orde 1
poly1 = lm(Y ~ X)
summary(poly1)
sqrt(summary(poly1)$r.squared)
mean(poly1$residuals^2)

## Orde 2
poly2 = lm(Y ~ poly(X, 2, raw = TRUE))
summary(poly2)
sqrt(summary(poly2)$r.squared) # Nilai R
mean(poly2$residuals^2)

## Orde 3
poly3 = lm(Y ~ poly(X, 3, raw = TRUE))
summary(poly3)
sqrt(summary(poly3)$r.squared) # Nilai R
mean(poly3$residuals^2)

## Orde 4
poly4 = lm(Y ~ poly(X, 4, raw = TRUE))
summary(poly4)
sqrt(summary(poly4)$r.squared) # Nilai R
mean(poly4$residuals^2)

## Orde 5
poly5 = lm(Y ~ poly(X, 5, raw = TRUE))
summary(poly5)
sqrt(summary(poly5)$r.squared) # Nilai R
mean(poly5$residuals^2)
```

```{r}
# Gabungkan model ke dalam list
models <- list(
  "Orde 1" = poly1,
  "Orde 2" = poly2,
  "Orde 3" = poly3,
  "Orde 4" = poly4,
  "Orde 5" = poly5
)

# Fungsi untuk mengambil metrik evaluasi
get_metrics <- function(model) {
  s <- summary(model)
  
  r_square <- s$r.squared
  adj_r_square <- s$adj.r.squared
  r_value <- sqrt(r_square)
  rse <- s$sigma
  mse <- mean(model$residuals^2)
  
  return(c(
    R = r_value,
    R_Square = r_square,
    Adj_R_Square = adj_r_square,
    RSE = rse,
    MSE = mse
  ))
}

# Buat tabel perbandingan
model_comparison <- as.data.frame(
  t(sapply(models, get_metrics))
)

# Rapikan hasil
model_comparison$Model <- rownames(model_comparison)
rownames(model_comparison) <- NULL

model_comparison <- model_comparison[, c(
  "Model", "R", "R_Square", "Adj_R_Square", "RSE", "MSE"
)]

model_comparison
```

```{r}
# ===================== Model dengan Orde 3 ===================== #
## Model 1
poly3 = lm(Y ~ poly(X, 3, raw = TRUE))
summary(poly3)
sqrt(summary(poly3)$r.squared)
# Konstanta tidak signifikan

## Model 2
poly3.2 = lm(Y ~ poly(X, 3, raw = TRUE)-1) # -1 di sini berfungsi agar konstanta tidak digunakan pada model
summary(poly3.2)
sqrt(summary(poly3.2)$r.squared)
# Koefisien x^2 tidak signifikan

## Model 3
poly3.3 = lm(Y ~ I(X) + I(X^3) - 1) # buat model secara manual agar X^2 tidak ikut menjadi model polynom
summary(poly3.3)
sqrt(summary(poly3.3)$r.squared)
```

```{r}
# Diagnostic Checking
# Hubungan Variabel Dependen dan Independen
pred = predict(poly3.3, newdata = list(x=X))
plot(X, Y, main="Degree-3 Polynomial",
     xlab="Hardwood Concentration", ylab="Tensile Strength", pch=19)
lines(X, pred, lwd = 2, col = "red")
```

```{r}
# Normalitas residual
poly3.3$residual
## Metode Histogram
hist(poly3.3$residual, main = "Histogram Residual", 
     xlab = "Residual", ylab = "Frekuensi", col = "lightblue")
## Metode QQ-Plot
qqnorm(poly3.3$residual, main = "Normal Q-Q Plot Residual")
qqline(poly3.3$residual)
## Metode Inferensi, menggunakan Shapiro-Wilk Test karena sampel < 50
shapiro.test(poly3.3$residual)
```

```{r}
# No-Autokorelasi Error
library(car)
durbinWatsonTest(poly3.3)
```

```{r}
# Runs test
# install.packages("randtests")
library(randtests)
runs.test(residuals(poly3.3))
```

# PERTEMUAN 9 REGRESI SPLINE
```{r}
#========Iterative Searching========#

x <- c(1:10, 13:22)
y <- numeric(20)
## Create first segment

set.seed(123)
y[1:10] <- 20:11 + rnorm(10, 0, 1.5)
## Create second segment

set.seed(123)
y[11:20] <- seq(11, 15, len=10) + rnorm(10, 0, 1.5)
x
y
## Plot it
par(mar=c(4,4,1,1)+0.2)
plot(x,y, ylim=c(0, 50), pch=16)
```

```{r}
# Knot
breaks <- x[which(x >= 1 & x <= 20)]

mse <- numeric(length(breaks))
for(i in 1:length(breaks)){
  piecewise1 <- lm(y ~ x*(x < breaks[i]) + x*(x>=breaks[i]))
  mse[i] <- summary(piecewise1)[6]
}
mse <- as.numeric(mse)
b1 <- breaks[which(mse==min(mse))]
b1
```

```{r}
# Regresi Spline
piecewise2 <- lm(y ~ x*(x < b1) + x*(x >= b1))
summary(piecewise2)
```

```{r}
# PLot
plot(x,y, ylim=c(5, 20), pch=16)
curve((8.61293 + 11.87676) + (0.31118-1.01519  )*x, add=T, from=1, to=8)
curve((8.61293 - 0.94203 ) + 0.31118 *x, add=T, from=8, to=max(x))
abline(v=8, lty=2)
```

```{r}
#========= Segmented Package========#
library(segmented)

lin.mod <- lm(y~x)
segmented.mod <- segmented(lin.mod, seg.Z = ~x, psi=14)
summary(segmented.mod)
```

```{r}
# plot
plot(x,y, pch=16, ylim=c(5,20))
plot(segmented.mod, add=T)
```

# PERTEMUAN 9 REGRESI SPLINE (1, 2, 3 Knot dengan linear, kuadratik, kubik)
```{r}
# Syntax setiap knot berbeda
```

